<?php

return
    '<?xml version="1.0" encoding="utf-8"?>
    <Response xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CitiesResponse">
        <ItemsCount>30056</ItemsCount>
        <MessageList />
        <CityList>
            <CityInfo>
                <City>Акъяр</City>
                <Region>Башкортостан респ.</Region>
                <District>Хайбуллинский</District>
                <AcPointCode>EM1679</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алабайтал</City>
                <Region>Оренбургская</Region>
                <District>Беляевский</District>
                <AcPointCode>REN002</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алабердино</City>
                <Region>Оренбургская</Region>
                <District>Тюльганский</District>
                <AcPointCode>EM14854</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алабино</City>
                <Region>Московская</Region>
                <District>Наро-Фоминский</District>
                <AcPointCode>MO0002</AcPointCode>
                <FiasId>9db42e9d-ce62-4a21-ab6d-925ba381015f</FiasId>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алабота </City>
                <Region>Омская</Region>
                <District>Русско-Полянский</District>
                <AcPointCode>EM11148</AcPointCode>
                <FiasId>3b822ee8-94e3-4851-9a88-de28e364ab78</FiasId>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алабуга</City>
                <Region>Челябинская</Region>
                <District>Красноармейский</District>
                <AcPointCode>CEK088</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алабуга</City>
                <Region>Татарстан респ.</Region>
                <District>Елабужский</District>
                <AcPointCode>NBC029</AcPointCode>
                <FiasId>82d4c783-5080-4faa-9cec-ba9152bc9fc8</FiasId>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алабуха</City>
                <Region>Московская</Region>
                <District>Дмитровский</District>
                <AcPointCode>MO3623</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алабушево</City>
                <Region>Московская</Region>
                <District>Солнечногорский</District>
                <AcPointCode>MO0003</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алагир</City>
                <Region>Северная Осетия-Алания респ.</Region>
                <District>Алагирский</District>
                <AcPointCode>OGZ001</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алагуй</City>
                <Region>Иркутская</Region>
                <District>Ольхонский</District>
                <AcPointCode>EM13752</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алаг-Шулун</City>
                <Region>Бурятия респ.</Region>
                <District>Окинский</District>
                <AcPointCode>EM5993</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Аладьино</City>
                <Region>Московская</Region>
                <District>Каширский</District>
                <AcPointCode>MO1995</AcPointCode>
                <FiasId>a054d62f-8272-40f3-be28-e82076763d5e</FiasId>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Аладьино</City>
                <Region>Рязанская</Region>
                <District>Чучковский</District>
                <AcPointCode>EM0011</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Аладьино</City>
                <Region>Московская</Region>
                <District>Дмитровский</District>
                <AcPointCode>MO1386</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алак</City>
                <Region>Дагестан респ.</Region>
                <District>Ботлихский</District>
                <AcPointCode>EM3807</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алакаевка</City>
                <Region>Самарская</Region>
                <District>Кинельский</District>
                <AcPointCode>SAM001</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алаксары</City>
                <Region>Чувашская респ. - Чувашия</Region>
                <District>Канашский</District>
                <AcPointCode>EM10738</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алакуртти</City>
                <Region>Мурманская</Region>
                <AcPointCode>APT021</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Аламасово</City>
                <Region>Нижегородская</Region>
                <District>Вознесенский</District>
                <AcPointCode>SAR014</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Аламбай</City>
                <Region>Алтайский край</Region>
                <District>Заринский</District>
                <AcPointCode>EM14059</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алан</City>
                <Region>Татарстан респ.</Region>
                <District>Тюлячинский</District>
                <AcPointCode>KAZ093</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алан-Бексер</City>
                <Region>Татарстан респ.</Region>
                <District>Высокогорский</District>
                <AcPointCode>EM15901</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Аландское</City>
                <Region>Оренбургская</Region>
                <District>Кваркенский</District>
                <AcPointCode>EM6514</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алапаевск</City>
                <Region>Свердловская</Region>
                <AcPointCode>SVX001</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алапурская</City>
                <Region>Ленинградская</Region>
                <District>Гатчинский</District>
                <AcPointCode>GTN146</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Аларь</City>
                <Region>Иркутская</Region>
                <District>Аларский</District>
                <AcPointCode>EM2833</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алатайкино</City>
                <Region>Марий Эл респ.</Region>
                <District>Килемарский</District>
                <AcPointCode>EM3401</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алаторка</City>
                <Region>Башкортостан респ.</Region>
                <District>Иглинский</District>
                <AcPointCode>EM12462</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алатырь</City>
                <Region>Чувашская респ. - Чувашия</Region>
                <AcPointCode>EM4154</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алачково</City>
                <Region>Московская</Region>
                <District>Чеховский</District>
                <AcPointCode>MO1416</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алашайка</City>
                <Region>Марий Эл респ.</Region>
                <District>Параньгинский</District>
                <AcPointCode>EM14863</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алашеевка</City>
                <Region>Мордовия респ.</Region>
                <District>Атяшевский</District>
                <AcPointCode>SSK054</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Албазино</City>
                <Region>Амурская</Region>
                <District>Сковородинский</District>
                <AcPointCode>EM7563</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Албахтино</City>
                <Region>Чувашская респ. - Чувашия</Region>
                <District>Красноармейский</District>
                <AcPointCode>CSY118</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алгазино</City>
                <Region>Чувашская респ. - Чувашия</Region>
                <District>Вурнарский</District>
                <AcPointCode>EM12503</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алгайский</City>
                <Region>Саратовская</Region>
                <District>Новоузенский</District>
                <AcPointCode>EM2324</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алгасово</City>
                <Region>Тамбовская</Region>
                <District>Моршанский</District>
                <AcPointCode>EM5816</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алгатуй</City>
                <Region>Иркутская</Region>
                <District>Тулунский</District>
                <AcPointCode>EM4054</AcPointCode>
                <FiasId>cbdc2b9e-0677-4fd0-8db0-a7b2df0c525f</FiasId>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алдан</City>
                <Region>Саха /Якутия/ респ.</Region>
                <District>Алданский</District>
                <AcPointCode>ADN</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алдаркино</City>
                <Region>Оренбургская</Region>
                <District>Бузулукский</District>
                <AcPointCode>EM13733</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алдиарово</City>
                <Region>Чувашская респ. - Чувашия</Region>
                <District>Янтиковский</District>
                <AcPointCode>EM9031</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алегазово</City>
                <Region>Башкортостан респ.</Region>
                <District>Мечетлинский</District>
                <AcPointCode>EM4161</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алеево</City>
                <Region>Московская</Region>
                <District>Ступинский</District>
                <AcPointCode>MO1602</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алеево</City>
                <Region>Рязанская</Region>
                <District>Чучковский</District>
                <AcPointCode>EM7179</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алейниково</City>
                <Region>Брянская</Region>
                <District>Стародубский</District>
                <AcPointCode>EM7256</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алейниково</City>
                <Region>Белгородская</Region>
                <District>Алексеевский</District>
                <AcPointCode>EM13890</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алейск</City>
                <Region>Алтайский край</Region>
                <AcPointCode>EM5156</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алеканово</City>
                <Region>Рязанская</Region>
                <District>Рязанский</District>
                <AcPointCode>RZN038</AcPointCode>
                <CashBan>false</CashBan>
            </CityInfo>
            <CityInfo>
                <City>Алекина Поляна</City>
                <Region>Татарстан респ.</Region>
                <District>Тетюшский</District>
                <AcPointCode>EM11819</AcPointCode>
                <CashBan>true</CashBan>
            </CityInfo>
        </CityList>
    </Response>';